# Generated by Django 5.0.3 on 2024-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайлы'},
        ),
        migrations.AddField(
            model_name='profile',
            name='accept',
            field=models.BooleanField(default=True, verbose_name='Согласие на отправку уведомлений на почту '),
        ),
        migrations.AddField(
            model_name='profile',
            name='male',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], default='male', max_length=6),
        ),
    ]
